spring:
  mail:
    host: smtp.gmail.com
    port: 587
#    host: smtp.naver.com
#    port: 587
    username: id@gmail.com
    password: password
    properties:
      mail:
        smtp:
#          ssl.enable: true
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/